TriggerReactor/TriggerReactor

src/main/resources/Executor/WORLD/DOORCLOSE.js
src/main/resources/Executor/WORLD/DOOROPEN.js
src/main/resources/Executor/WORLD/DOORTOGGLE.js
src/main/resources/Executor/WORLD/DROPITEM.js
src/main/resources/Executor/WORLD/FALLINGBLOCK.js
src/main/resources/Executor/WORLD/ITEMFRAMEROTATE.js
src/main/resources/Executor/WORLD/ITEMFRAMESET.js
src/main/resources/Executor/WORLD/LEVEROFF.js
src/main/resources/Executor/WORLD/LEVERON.js
src/main/resources/Executor/WORLD/LEVERTOGGLE.js
src/main/resources/Executor/WORLD/SETBLOCK.js
src/main/resources/Executor/WORLD/SIGNEDIT.js

Every executor has been tested and works correctly. Feel free to edit them if you want. They are all in a folder called WORLD.
Executors and parameters:
#DOORCLOSE    [location<location or number number number>]
Closes the door (or trapdoor or fence) at the given location.
#DOOROPEN     [location<location or number number number>]
Opens the door at the given location.
#DOORTOGGLE [location<location or number number number>]
Toggles the door state at a given location.
#DROPITEM [item<string or number>, quantity<number>, Enchantments<string>, location<location or number number number>]
Spawns a item in the given location.
Every item name must be one from the materials enum: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
Enchantments must be "none" or a list of …

12 New Executors for World Editing

---

src/main/resources/Executor/EFFECT/BURN.js
src/main/resources/Executor/EFFECT/EXPLOSION.js
src/main/resources/Executor/EFFECT/LIGHTNING.js
src/main/resources/Executor/EFFECT/PUSH.js
src/main/resources/Executor/SOUNDALL.js
src/main/resources/Executor/WORLD/DOORCLOSE.js
src/main/resources/Executor/WORLD/DOOROPEN.js
src/main/resources/Executor/WORLD/DOORTOGGLE.js
src/main/resources/Executor/WORLD/DROPITEM.js
src/main/resources/Executor/WORLD/FALLINGBLOCK.js
src/main/resources/Executor/WORLD/LEVERON.js
src/main/resources/Executor/WORLD/LEVERTOGGLE.js
src/main/resources/Executor/WORLD/SETBLOCK.js

Ok I deleted my fork and restarted from scratch :)
Fixed SOUNDALL executor.
Made WORLD executors to schedule world changes with BukkitScheduler so they can be safely used in Async scripts (All except 3, ITEMFRAMEROTATE, ITEMFRAMESET, and SIGNEDIT. Lack of time).
Added 4 NEW EFFECT Executors.
1. PUSH: pushes entity. Args: [entity or playername in string], number number number. The 3 numbers are the force in all three axis.
2. BURN: Burns the entity for the specified amount of seconds. Args: [entity or playername in string], number.
3. EXPLOSION: Makes explosion in provided location: Args: number (power, capped at 20.0) and location (as always can use three numbers).
4. LIGHTNING: Strikes lightning in given location. Args: boolean(whether or not the lightning does damage) and location (can …

Fixes and New Executors

---

src/main/java/io/github/wysohn/triggerreactor/bukkit/manager/trigger/share/CommonFunctions.java

Only changes is I expanded upon the random() function in CommonFunctions.java to be able to take and return any number value type rather than just int, and added a new function for rounding doubles to a set decimal place for cleaner display in strings.

Expanded CommonFunctions

---

src/main/java/io/github/wysohn/triggerreactor/bukkit/manager/trigger/share/CommonFunctions.java
src/main/resources/plugin.yml

Tested and operating functionally on my server as we speak

Added optional integer argument to headForName()

---

src/main/java/io/github/wysohn/triggerreactor/core/script/lexer/Lexer.java
src/test/java/io/github/wysohn/triggerreactor/core/script/interpreter/TestInterpreter.java

This PR adds support for CR Characters,
which is line break for Mac OS and Linux Systems

Resolves Extra Issues of #105 - Added Support for CR (\r) Characters

---

src/main/resources/Executor/Bukkit/TP.js
src/main/resources/Placeholder/Bukkit/round.js

$round
수를 반올림합니다.
1. 인자가 1개 올경우 해당 수를 소숫점 위로 반올림합니다.
ex) $round:3.555 = 4
2. 인자가 2개 올 경우 소숫점을 설정할 수 있습니다. ($round:소수:소숫점)
ex) $round:3.564:1 = 3.6
#TP 
플레이어를 tp 합니다. (#TP x,y,z,pitch,yaw)

$round:double:decimal_point / #TP x,y,z,pitch,yaw

---

src/main/resources/Placeholder/Bukkit/firstgroup.js
src/main/resources/Placeholder/Sponge/firstgroup.js

This placeholder returns player's first group.

New placeholder $firstgroup

---

core/src/main/java/io/github/wysohn/triggerreactor/core/script/Token.java
core/src/main/java/io/github/wysohn/triggerreactor/core/script/interpreter/Interpreter.java
core/src/main/java/io/github/wysohn/triggerreactor/core/script/lexer/Lexer.java
core/src/main/java/io/github/wysohn/triggerreactor/core/script/parser/Parser.java
core/src/test/java/io/github/wysohn/triggerreactor/core/script/interpreter/TestInterpreter.java
core/src/test/java/io/github/wysohn/triggerreactor/core/script/lexer/TestLexer.java
core/src/test/java/io/github/wysohn/triggerreactor/core/script/parser/TestParser.java

I let "--" be always recognized as a unary decrement operator, so operations like "1--1" don't work anymore. You'll have to add a space between them.

Added unary increment/decrement operators

---

core/src/main/java/io/github/wysohn/triggerreactor/core/main/TriggerReactorCore.java
core/src/main/java/io/github/wysohn/triggerreactor/core/manager/trigger/inventory/AbstractInventoryTriggerManager.java

파일 관리를 더 유연하게 하기 위하여 인벤토리 타이틀 부분과 파일 명을 분리했습니다.
To make file management more flexible, I separated the file name from title part.
command:
/triggerreactor[trg] inventory[i] <name> settitle <title>

InventoryTrigger Custom Title

---

core/src/main/java/io/github/wysohn/triggerreactor/core/script/interpreter/Interpreter.java

Fix #437 - CATCH Statement is not return fundemental error. 

---

build.gradle
core/src/main/java/io/github/wysohn/triggerreactor/core/script/interpreter/Interpreter.java
core/src/main/java/io/github/wysohn/triggerreactor/core/script/lexer/Lexer.java
core/src/main/java/io/github/wysohn/triggerreactor/core/script/parser/Parser.java
core/src/test/java/io/github/wysohn/triggerreactor/core/script/interpreter/TestInterpreter.java

Add `import as` spec

---

bukkit/src/main/resources/Placeholder/isnumber.js

Fix regex for isnumber placeholder

---

core/src/main/java/io/github/wysohn/triggerreactor/core/script/parser/Parser.java
core/src/test/java/io/github/wysohn/triggerreactor/core/script/interpreter/TestInterpreter.java
core/src/test/java/io/github/wysohn/triggerreactor/core/script/parser/TestParser.java

fix: Inconsistent behavior of literal string "true"/"false"

---

bukkit/src/main/resources/Executor/TP.js

Closes #464, also closes #455
Embraced validation to support more overloading, more flexibility.

fix: Executor #TP need to verify its input

---

build.gradle
bukkit/src/main/resources/Executor/MESSAGE.js

Color even if PlaceholderAPI

---

core/src/main/java/io/github/wysohn/triggerreactor/core/config/InvalidTrgConfigurationException.java
core/src/main/java/io/github/wysohn/triggerreactor/core/main/TriggerReactorCore.java
core/src/main/java/io/github/wysohn/triggerreactor/core/manager/trigger/TriggerConfigKey.java
core/src/main/java/io/github/wysohn/triggerreactor/core/manager/trigger/TriggerInfo.java
core/src/main/java/io/github/wysohn/triggerreactor/core/manager/trigger/area/AbstractAreaTriggerManager.java
core/src/main/java/io/github/wysohn/triggerreactor/core/manager/trigger/command/AbstractCommandTriggerManager.java
core/src/main/java/io/github/wysohn/triggerreactor/core/manager/trigger/custom/AbstractCustomTriggerManager.java
core/src/main/java/io/github/wysohn/triggerreactor/core/manager/trigger/inventory/AbstractInventoryTriggerManager.java
core/src/main/java/io/github/wysohn/triggerreactor/core/manager/trigger/repeating/AbstractRepeatingTriggerManager.java
core/src/main/java/io/github/wysohn/triggerreactor/tools/ValidationUtil.java
core/src/test/java/io/github/wysohn/triggerreactor/core/manager/trigger/TriggerInfoTest.java

https://github.com/TriggerReactor/TriggerReactor/pull/480/files
This should fix the mentioned problem
refactor_dagger will be abandoned for now cause it would break too much things (will try again with part by part at the time though)
---
Haven't tested it in-game yet

Development inconsistent json

---

core/src/main/java/io/github/wysohn/triggerreactor/core/script/interpreter/lambda/LambdaFunction.java

fix-issue-546 [master branch]

---

core/src/main/java/io/github/wysohn/triggerreactor/core/script/lexer/Lexer.java

Fix that being panicked by passing "0" at the last

---

bukkit/src/main/resources/Executor/VELOCITY.js
bukkit/src/test/java/js/executor/AbstractTestExecutors.java

Fixes #582, superseded by #586

Fix that #VELOCITY Executor

---

core/src/main/java/io/github/wysohn/triggerreactor/core/config/source/GsonConfigSource.java
core/src/main/java/io/github/wysohn/triggerreactor/core/config/source/IConfigSource.java

Readable identifier on calling `#toString()`

---

core/src/main/java/io/github/wysohn/triggerreactor/core/config/source/GsonConfigSource.java

---
Download the jar for this pull request: [TriggerReactor-618.zip](https://nightly.link/TriggerReactor/TriggerReactor/actions/artifacts/1000236655.zip)

use atomic flag

---

core/src/main/java/io/github/wysohn/triggerreactor/tools/FileUtil.java

---
Download the jar for this pull request: [TriggerReactor-621.zip](https://nightly.link/TriggerReactor/TriggerReactor/actions/artifacts/1028764220.zip)

explicitly specify charset as utf8

---

core/src/main/java/io/github/wysohn/triggerreactor/core/script/interpreter/Interpreter.java
core/src/test/java/io/github/wysohn/triggerreactor/core/script/interpreter/TestInterpreter.java

Fixes #623
---
Download the jar for this pull request: [TriggerReactor-625.zip](https://nightly.link/TriggerReactor/TriggerReactor/actions/artifacts/1024551542.zip)

fix: switch case with eps parameter type

---

core/src/main/java/io/github/wysohn/triggerreactor/core/manager/trigger/command/CommandTriggerManager.java

---
Download the jar for this pull request: [TriggerReactor-638.zip](https://nightly.link/TriggerReactor/TriggerReactor/actions/artifacts/1167960175.zip)

allow executing command trigger from console
